services:
  - type: web
    name: outflo-server
    env: node
    buildCommand: |
      cd server
      npm install
      npm run build
    startCommand: |
      cd server
      node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        fromDatabase:
          name: outflo-db
          property: connectionString 